keys:
  - &thinkbook age1tpn3wn4l0vypr9wakz58smqcpznvuhrfc7p5gp0qnxteedadjg7qxph860
  - &homelab age1mws2js7l050fry5hx265rnkq8ayfvf6urp6ecjmr250quj3e2cmsnpa9vj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *thinkbook
      - *homelab
