# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    };
    kernelModules = [ "kvm-amd" "nvidia_modeset" "nvidia" "nvidia_uvm" "nvidia_drm" ];
    loader = {
      systemd-boot ={
        enable = true;
        configurationLimit = 42;
      };
      efi.canTouchEfiVariables = true;
      efi.efiSysMountPoint = "/boot/efi";
    };
    extraModulePackages = [ ];
  };
    # Use the systemd-boot EFI boot loader.
 

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9eb3038f-d611-4dcd-a22a-d88320fb6a03";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/34EE-2279";
      fsType = "vfat";
    };

  services.xserver = {
    videoDrivers = [ "nvidia" ];
    excludePackages = [ pkgs.xterm ];
  };

    hardware = {
    opengl = {
      enable = true;
      extraPackages = with pkgs; [
        nvidia-vaapi-driver
        vaapiVdpau
        libvdpau-va-gl
      ];
    };
    nvidia = {
      package = config.boot.kernelPackages.nvidiaPackages.latest;
      modesetting.enable = true;
      powerManagement.enable = true;
    };
    bluetooth.enable = true;
  };

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
