# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, pkgs, config, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader = {
      efi.canTouchEfiVariables = true;
      systemd-boot.enable = lib.mkForce false;
      systemd-boot.configurationLimit = 5;
    };
    lanzaboote = {
      enable = true;
      pkiBundle = "/etc/secureboot";
    };
    bootspec.enable = true;
    initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" "samsung-galaxybook" ];
    extraModulePackages = [
      (config.boot.kernelPackages.callPackage ../../packages/samsung-kernel.nix { })
    ];
    kernelParams = [ "i915.enable_dpcd_backlight=3" "i915.force_probe=46a8" ];
    extraModprobeConfig = ''
      options snd slots=snd-hda-intel
      options snd-hda-intel model=alc256-samsung-headphone
    '';
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/d64386ae-2d82-4882-b144-41fcc54bda4b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/EDF0-6924";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "umask=0077" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/8d906469-9587-47bb-be8e-9a921e32515d";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/2196153d-184d-41fe-a541-23767454b1cf";
      fsType = "ext4";
    };

  swapDevices = [
    {
      device = "/dev/nvme0n1p5";
      randomEncryption = true;
    }
  ];

  networking.hostName = "dvision-notebook";

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vaapiVdpau
      libvdpau-va-gl
    ];
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  hardware.enableAllFirmware = true;

  time.hardwareClockInLocalTime = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefaulthardware.enableRedistributableFirmware;
}
